env:
  global:
  - secure: aJlKolNKHbVX+pYz05SQbjDEFGIJJNXaiCxoftw4Ni8ro2i7r+LPxdF5GtyZPtaIk4Hp8qjKAZqxObStiOL9nAM/yx6SZ5TR/Lu+dMIdH3Z21Zv++dKS3q2kDg6yOgNn8l3TyvPnOZZQNHGwNB0ycbwO+cJYQTAf7kQF9fhSqR+BEFvHuKZ3Cc9C3v9Hca6F7fFWZqdNXIs06aTVRAtw1QEOfVyaOyuGlXSVdjUYIhO7Nx2D3aUxtpsXQDtLMXAcvcNifOTRZAMOvLH2koLEAOe/odyTZ+k2YDPGGs9ajIbftP6uCLSG2KXlMY9MKv2EpCwLrcbrmmlC5kIOpK5pPITlIn4sCLoYjEchnUgGv857FtFFXY6uJQ6A8Ruwd7Z19UHD/PWBmakf6IZIowCtXxfVxwosC7Xb6T9wEBn0XiwxlyR20DM9f0MEtPYc08jKn+/LJNEZ/LVPNZABpkowKMN1ItrtPRXPCJsz+UZhf2FJ+9bZrziSxHkHbKSRePLp+/RXfnDlyawoVjUvzFYdUuHpBmO9QmkaFo1J7EHDatcV0YuMB5k4uuRxyM6wEUnMU2lXwbIqnYM16hu7O4QQEc2mi3Ijv2PQPInnZxFuYZ8CLgThiP/RfwSqak7un018pxZ4aCpFC6W2oSQDOXUH85HUsRCHcnoD97NJhWqygZo=
  - secure: nxiZyMdvWT1KiA+FKqS0tUOZWHq/9XGvximyp+l/rBTDoNwC7nJcPGqH/ofXJt0PQArFId5FXApORY9ZMSrr3b6P7bn2+OYqeYaGECKlMuhbccUy0jzBN/sbkVSptxhSzEh91ngqN6/bkcxhHiWc+NP1EwXxgRYd90NfeMEMC9KUo1uHEMFmGjL0Bsyl8OTnV26Sq8lQoIxMCFEKzp83xL/M9vHMfAYXY6dHPYmEYb/xuZXXsYCqan4AeOrHxX9oCuRSjX4qrXXR2HZ+TbnQ6lVgHLK4IsNb7VMA5XVHvLrXB+HG+1PAawZPeEo6Tw/m0T7hUWeBGbtH2VYpAZLoGF0NrEUIAX/uQbid+XgjDreyd7lYLpG2ejCUBOGIUvVfreuJKExQJUMzneoQMX6Hlbf2EiTnb1MSo9OzgHRs0tEEr8GNZ+XAxEw3Z91izec1miVr2YhvdTfGyhAS8CA/HSALC49ZHGWe4eL+1libu5306uV7jDnChuFWUU0nplhJfJ21RU66hbO5QvFbEZVILGvaRPNo7Pub5X8wfRjA99v7VmgxA8VLyAG2dW8yKp1TtaijUUad/OuM//vZX1G6JjGQ5hOvFM/W86cA4QyFDMRbgGrDwiIQQDj/Md+h5oITHF9RJ+z2+UubjWn+lM6iWQeXaQ+5AzwNEuDLC74uIwk=
script:
- ls
before_deploy:
- npm install gulp
- npm install gulp -g
- npm install vinyl-ftp gulp-util minimist --save-dev
deploy:
  skip_cleanup: true
  provider: script
  script: gulp deploy --user $FTP_USER --password $FTP_PASSWORD
  on:
    tags: true
