env:
  global:
  - secure: aJlKolNKHbVX+pYz05SQbjDEFGIJJNXaiCxoftw4Ni8ro2i7r+LPxdF5GtyZPtaIk4Hp8qjKAZqxObStiOL9nAM/yx6SZ5TR/Lu+dMIdH3Z21Zv++dKS3q2kDg6yOgNn8l3TyvPnOZZQNHGwNB0ycbwO+cJYQTAf7kQF9fhSqR+BEFvHuKZ3Cc9C3v9Hca6F7fFWZqdNXIs06aTVRAtw1QEOfVyaOyuGlXSVdjUYIhO7Nx2D3aUxtpsXQDtLMXAcvcNifOTRZAMOvLH2koLEAOe/odyTZ+k2YDPGGs9ajIbftP6uCLSG2KXlMY9MKv2EpCwLrcbrmmlC5kIOpK5pPITlIn4sCLoYjEchnUgGv857FtFFXY6uJQ6A8Ruwd7Z19UHD/PWBmakf6IZIowCtXxfVxwosC7Xb6T9wEBn0XiwxlyR20DM9f0MEtPYc08jKn+/LJNEZ/LVPNZABpkowKMN1ItrtPRXPCJsz+UZhf2FJ+9bZrziSxHkHbKSRePLp+/RXfnDlyawoVjUvzFYdUuHpBmO9QmkaFo1J7EHDatcV0YuMB5k4uuRxyM6wEUnMU2lXwbIqnYM16hu7O4QQEc2mi3Ijv2PQPInnZxFuYZ8CLgThiP/RfwSqak7un018pxZ4aCpFC6W2oSQDOXUH85HUsRCHcnoD97NJhWqygZo=
  - secure: i9QIjDbDQ9sWgl3ZC6ZiHWvekYHogAnPXYcuKMLN0guuQjhwIOyRnpdoBWw8Kn9OBZKlhg7/a1sE775Xt1naxnFpM4mvfTdhXi5KI4qOO7YkuvPVB2GR89J2DW7zJJeOmS393wKijtIm7IggSaacwP6qVouGJ9HQLNs+USiyHyPUtLDDkUNFaalKDXXLGZB0K1T0AadkuA7amhUAezhR54VlBRcIcHRQkj9lr9+BugY/g1cfWWWEYB2lsSP2J0jxN4vzQ6JdoMgKuUddCFRRjPxiDJJIxw3PmIarAje7Ff+MIA6vjIV0yHh+8AhJ2CvHHJxiUXDofKGCRz/mPdpNLYTEHgCrGRMF01EZQsCyvhFu2zfxKLggDXQ6jKkFKULC1EvgPmxI1OXEezeYC7fqwXFoP/+IL173TivJPIUDeLRHxwa6vzXonz31p3A54BpXg55qIXkVw1VRT+WZ66SuGyuQ+NqPWDrXaSkqE2XdyOJx2fmR8ubxnyNvptFHd1gFYSzIp4DwgvmoaingmQktXIaeYx/v55Kkb4awWihOpOxcySsFGKkRFaa/WZOMFTPSU1Z3ZX3D9fAhAwZ+qhnhOrpmg3sQBQyCdvoV7bL5KmwsPfFMHXA6rUFnBICJ5TMvbDhmfYcUOxbrVSjfEqgkbH3OCppyOYsEO9zrum1RmLw=
script:
  - ls
before_deploy:
- npm install gulp
- npm install gulp -g
- npm install vinyl-ftp gulp-util minimist --save-dev
deploy:
  skip_cleanup: true
  provider: script
  script: gulp deploy --user $FTP_USER --password $FTP_PASSWORD
  on:
    tags: true
